
Basic Imports

In [6]:
pip install numpy pandas matplotlib seaborn scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python312\site-packages (2.4.6)
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     -------------------------------------- - 51.2/52.8 kB 2.6 MB/s eta 0:00:01
     -------------------------------------- 52.8/52.8 kB 906.3 kB/s eta 0:00:00
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl.metadata (121 kB)
     ---------------------------------------- 0.0/121.0 kB ? eta -:--:--
     ----------------------------------- -- 112.6/121.0 kB 3.3 MB/s eta 0:00:01
     -------------------------------------- 121.0/121.0 kB 2.4 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
    --------------------------------------- 0.2/9.8 MB 5.6 MB/s eta 0:00:02
    --------------------------------------- 0.2/9.8 MB 2.9 MB/s eta 0:00:04
   - -------------------------------------- 0.3/9.8 MB 2.4 MB/s eta 0:00:04
   - -------------------------------------- 0.3/9.8 MB 2.3 MB/s eta 0:00:05
   - -------------------------------------- 0.4/9.8 MB 1.9 MB/s eta 0:00:05
   - -------------------------------------- 0.5/9.8 MB 1.9 MB/s eta 0:00:05
   - -------------------------------------- 0.5/9.8 MB 1.9 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/9.8 MB 1.7 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/9.8 MB 1.7 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.8 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.9/9.8 MB 1.5 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/9.8 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.8 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.1/9.8 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.1/9.8 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.8 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.8 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.4/9.8 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.4/9.8 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.4/9.8 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.4/9.8 MB 1.4 MB/s eta 0:00:06
   ------ --------------------------------- 1.5/9.8 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.7/9.8 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.8 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.8 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.8 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.9/9.8 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.9/9.8 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.0/9.8 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.8 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.2/9.8 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.2/9.8 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.3/9.8 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.3/9.8 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.3/9.8 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.4/9.8 MB 1.3 MB/s eta 0:00:06
   ---------- ----------------------------- 2.5/9.8 MB 1.4 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.8 MB 1.4 MB/s eta 0:00:06
   ---------- ----------------------------- 2.7/9.8 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.7/9.8 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.8/9.8 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.8/9.8 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.8 MB 1.4 MB/s eta 0:00:06
   ------------ --------------------------- 3.0/9.8 MB 1.4 MB/s eta 0:00:06
   ------------ --------------------------- 3.0/9.8 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 3.2/9.8 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 3.3/9.8 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 3.3/9.8 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.8 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.4/9.8 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.5/9.8 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.5/9.8 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.6/9.8 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.7/9.8 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.7/9.8 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.8/9.8 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.9/9.8 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 4.0/9.8 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 4.0/9.8 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 4.1/9.8 MB 1.3 MB/s eta 0:00:05
   ----------------- ---------------------- 4.2/9.8 MB 1.3 MB/s eta 0:00:05
   ----------------- ---------------------- 4.2/9.8 MB 1.3 MB/s eta 0:00:05
   ----------------- ---------------------- 4.3/9.8 MB 1.3 MB/s eta 0:00:05
   ----------------- ---------------------- 4.3/9.8 MB 1.3 MB/s eta 0:00:05
   ------------------ --------------------- 4.4/9.8 MB 1.3 MB/s eta 0:00:05
   ------------------ --------------------- 4.5/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 4.6/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.6/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.8/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.8/9.8 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.9/9.8 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 4.9/9.8 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 5.1/9.8 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.8 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 5.3/9.8 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 5.3/9.8 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.4/9.8 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.8 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.8 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.6/9.8 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.7/9.8 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.7/9.8 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.8 MB 1.3 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 5.9/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 6.1/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 6.1/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 6.2/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 6.4/9.8 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 6.5/9.8 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 6.5/9.8 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.8 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.6/9.8 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.7/9.8 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.7/9.8 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 6.9/9.8 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 6.9/9.8 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 7.0/9.8 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.8 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.8 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 7.2/9.8 MB 1.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.2/9.8 MB 1.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.4/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.4/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.5/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.5/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 7.7/9.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 7.8/9.8 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 7.8/9.8 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 8.0/9.8 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 8.0/9.8 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 8.2/9.8 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 8.3/9.8 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 8.3/9.8 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 8.5/9.8 MB 1.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.6/9.8 MB 1.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.8/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.8/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.1/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.1/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 9.3/9.8 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 9.3/9.8 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 9.5/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.3 MB/s eta 0:00:00
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
    --------------------------------------- 0.1/8.2 MB 8.3 MB/s eta 0:00:01
    --------------------------------------- 0.2/8.2 MB 2.9 MB/s eta 0:00:03
   - -------------------------------------- 0.3/8.2 MB 2.2 MB/s eta 0:00:04
   - -------------------------------------- 0.3/8.2 MB 2.0 MB/s eta 0:00:05
   - -------------------------------------- 0.4/8.2 MB 1.8 MB/s eta 0:00:05
   -- ------------------------------------- 0.4/8.2 MB 1.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/8.2 MB 1.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/8.2 MB 1.6 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/8.2 MB 1.5 MB/s eta 0:00:05
   --- ------------------------------------ 0.7/8.2 MB 1.5 MB/s eta 0:00:05
   --- ------------------------------------ 0.7/8.2 MB 1.5 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/8.2 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 0.9/8.2 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 0.9/8.2 MB 1.5 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/8.2 MB 1.4 MB/s eta 0:00:06
   ----- ---------------------------------- 1.0/8.2 MB 1.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.1/8.2 MB 1.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.2/8.2 MB 1.4 MB/s eta 0:00:05
   ----- ---------------------------------- 1.2/8.2 MB 1.4 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.2 MB 1.4 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.2 MB 1.4 MB/s eta 0:00:05
   ------ --------------------------------- 1.4/8.2 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.5/8.2 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.5/8.2 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.2 MB 1.4 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.2 MB 1.4 MB/s eta 0:00:05
   -------- ------------------------------- 1.7/8.2 MB 1.4 MB/s eta 0:00:05
   -------- ------------------------------- 1.8/8.2 MB 1.4 MB/s eta 0:00:05
   -------- ------------------------------- 1.8/8.2 MB 1.4 MB/s eta 0:00:05
   --------- ------------------------------ 1.9/8.2 MB 1.4 MB/s eta 0:00:05
   --------- ------------------------------ 1.9/8.2 MB 1.4 MB/s eta 0:00:05
   --------- ------------------------------ 2.0/8.2 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.2 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.2 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.2/8.2 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.2/8.2 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.3/8.2 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.2 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.2 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 2.5/8.2 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 2.5/8.2 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.2 MB 1.3 MB/s eta 0:00:05
   ------------ --------------------------- 2.7/8.2 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 2.7/8.2 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 2.8/8.2 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 2.8/8.2 MB 1.3 MB/s eta 0:00:04
   ------------- -------------------------- 2.8/8.2 MB 1.3 MB/s eta 0:00:04
   ------------- -------------------------- 2.8/8.2 MB 1.3 MB/s eta 0:00:04
   -------------- ------------------------- 3.0/8.2 MB 1.3 MB/s eta 0:00:04
   -------------- ------------------------- 3.1/8.2 MB 1.3 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.2 MB 1.3 MB/s eta 0:00:04
   --------------- ------------------------ 3.2/8.2 MB 1.3 MB/s eta 0:00:04
   --------------- ------------------------ 3.3/8.2 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.3/8.2 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.2 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.5/8.2 MB 1.3 MB/s eta 0:00:04
   ----------------- ---------------------- 3.5/8.2 MB 1.3 MB/s eta 0:00:04
   ----------------- ---------------------- 3.6/8.2 MB 1.3 MB/s eta 0:00:04

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
pip install wordcloud

Defaulting to user installation because normal site-packages is not writeable
Collecting wordcloud
  Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.19.3 in c:\users\user\appdata\roaming\python\python312\site-packages (from wordcloud) (2.4.6)
Requirement already satisfied: pillow in c:\users\user\appdata\roaming\python\python312\site-packages (from wordcloud) (12.2.0)
Requirement already satisfied: matplotlib in c:\users\user\appdata\roaming\python\python312\site-packages (from wordcloud) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python312\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl (307 kB)
   ---------------------------------------- 0.0/307.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/307.2 kB ? eta -:--:--
   ---------------------------------------- 0.0/307.2 kB ? eta -:--:--
   - -------------------------------------- 10.2/307.2 kB ? eta -:--:--
   -- ------------------------------------ 20.5/307.2 kB 217.9 kB/s eta 0:00:02
   -- ------------------------------------ 20.5/307.2 kB 217.9 kB/s eta 0:00:02
   -- ------------------------------------ 20.5/307.2 kB 217.9 kB/s eta 0:00:02
   ------------ ------------------------- 102.4/307.2 kB 393.8 kB/s eta 0:00:01
   -------------------------------- ----- 266.2/307.2 kB 966.0 kB/s eta 0:00:01
   -------------------------------------- 307.2/307.2 kB 951.9 kB/s eta 0:00:00
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\user\appdata\roaming\python\python312\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.5 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.5 kB ? eta -:--:--
     ------------------ ------------------- 20.5/41.5 kB 108.9 kB/s eta 0:00:01
     -------------------------------------  41.0/41.5 kB 196.9 kB/s eta 0:00:01
     -------------------------------------- 41.5/41.5 kB 166.1 kB/s eta 0:00:00
Collecting tqdm (from nltk)
  Downloading tqdm-4.68.2-py3-none-any.whl.metadata (58 kB)
     ---------------------------------------- 0.0/58.7 kB ? eta -:--:--
     --------------------------- ------------ 41.0/58.7 kB 1.9 MB/s eta 0:00:01
     ---------------------------------------- 58.7/58.7 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---- ----------------------------------- 0.2/1.6 MB 5.3 MB/s eta 0:00:01
   ----- ---------------------------------- 0.2/1.6 MB 3.5 MB/s eta 0:00:01
   ------- -------------------------------- 0.3/1.6 MB 2.2 MB/s eta 0:00:01
   --------- ------------------------------ 0.4/1.6 MB 2.0 MB/s eta 0:00:01
   --------- ------------------------------ 0.4/1.6 MB 1.9 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.6 MB 1.5 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.6 MB 1.7 MB/s eta 0:00:01
   --------------- ------------------------ 0.6/1.6 MB 1.6 MB/s eta 0:00:01
   --------------- ------------------------ 0.6/1.6 MB 1.6 MB/s eta 0:00:01
   --------------- ------------------------ 0.6/1.6 MB 1.6 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.6 MB 1.5 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.6 MB 1.5 MB/s eta 0:00:01
   ---------------------- ----------------- 0.9/1.6 MB 1.5 MB/s eta 0:00:01
   ---------------------- ----------------- 0.9/1.6 MB 1.5 MB/s eta 0:00:01
   -------------------------- ------------- 1.0/1.6 MB 1.5 MB/s eta 0:00:01
   --------------------------- ------------ 1.1/1.6 MB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 1.1/1.6 MB 1.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.2/1.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 1.2/1.6 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 1.4/1.6 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 1.4/1.6 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 1.4/1.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  1.5/1.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 1.3 MB/s eta 0:00:00
Downloading regex-2026.5.9-cp312-cp312-win_amd64.whl (277 kB)
   ---------------------------------------- 0.0/277.8 kB ? eta -:--:--
   ------------------------- -------------- 174.1/277.8 kB 3.5 MB/s eta 0:00:01
   ------------------------- -------------- 174.1/277.8 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------  276.5/277.8 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 277.8/277.8 kB 1.9 MB/s eta 0:00:00
Downloading click-8.4.1-py3-none-any.whl (116 kB)
   ---------------------------------------- 0.0/116.6 kB ? eta -:--:--
   -------------------------------------- - 112.6/116.6 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 116.6/116.6 kB 1.7 MB/s eta 0:00:00
Downloading tqdm-4.68.2-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.6 kB ? eta -:--:--
   -------------------- ------------------- 41.0/78.6 kB ? eta -:--:--
   ---------------------------------------- 78.6/78.6 kB 1.1 MB/s eta 0:00:00
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.4.1 nltk-3.9.4 regex-2026.5.9 tqdm-4.68.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
# Importing necessary libraries
import numpy as np        # For numerical operations
import pandas as pd       # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
%matplotlib inline

# Importing WordCloud for text visualization
from wordcloud import WordCloud

# Importing NLTK for natural language processing
import nltk
from nltk.corpus import stopwords    # For stopwords


# Downloading NLTK data
nltk.download('stopwords')   # Downloading stopwords data
nltk.download('punkt_tab')       # Downloading tokenizer data

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [25]:
# Read the CSV file
df = pd.read_csv('spam.csv')

# Display the first few rows of the DataFrame
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [26]:
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [27]:
# Rename the columns name
df.rename(columns = {'v1': 'target', 'v2': 'text'}, inplace = True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...


Data Preprocessing

In [28]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [29]:
#check duplicate values
df.duplicated().sum()

np.int64(403)

In [30]:

len(df)

5572

In [31]:
#remove Duplicate
df = df.drop_duplicates(keep = 'first')
len(df)

5169

Feature Engg

In [32]:
# Importing the Porter Stemmer for text stemming
from nltk.stem.porter import PorterStemmer

# Importing the string module for handling special characters
import string

# Creating an instance of the Porter Stemmer
ps = PorterStemmer()

In [33]:
# Lowercase transformation and text preprocessing function
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [34]:
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [35]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [36]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [37]:

X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state = 2)

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [41]:

svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)

In [42]:

clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    
    
}


Model Evaluation

In [43]:
from sklearn.metrics import accuracy_score, precision_score
def train_classifier(clfs, X_train, y_train, X_test, y_test):
    clfs.fit(X_train,y_train)
    y_pred = clfs.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy , precision

In [44]:
accuracy_scores = []
precision_scores = []
for name , clfs in clfs.items():
    current_accuracy, current_precision = train_classifier(clfs, X_train, y_train, X_test, y_test)
    print()
    print("For: ", name)
    print("Accuracy: ", current_accuracy)
    print("Precision: ", current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  SVC
Accuracy:  0.9671179883945842
Precision:  0.9333333333333333

For:  KNN
Accuracy:  0.9274661508704062
Precision:  1.0

For:  NB
Accuracy:  0.9709864603481625
Precision:  0.9655172413793104

For:  DT
Accuracy:  0.937137330754352
Precision:  0.9010989010989011

C:\Users\User\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\User\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

For:  LR
Accuracy:  0.9632495164410058
Precision:  0.9629629629629629

For:  RF
Accuracy:  0.9700193423597679
Precision:  0.9421487603305785

For:  Adaboost
Accuracy:  0.9235976789168279
Precision:  0.8734177215189873

For:  Bgc
Accuracy:  0.9622823984526112
Precision:  0.9024390243902439

For:  ETC
Accuracy:  0.9709864603481625
Precision:  0.921875

For:  GBDT
Accuracy:  0.9497098646034816
Precision:  0.93